#这是一个基本的工作流程，可以帮助您开始使用Actions

姓名: 词

#控制工作流何时运行
在:
  #在推或拉请求事件上触发工作流，但仅针对"主"分支
推:
分支机构: [ “主要的”]
合并请求:
分支机构: [ “主要的”]

  #允许您从"操作"选项卡手动运行此工作流
工作流_分派:

#一个工作流运行由一个或多个作业组成，这些作业可以顺序运行，也可以并行运行
工作:
  #此工作流包含一个名为"构建"的单一作业
建造:
    #作业将在其上运行的运行器类型
奔跑: Ubuntu最新版

    #步骤表示将作为作业的一部分执行的任务序列
步骤:
      #在$GitUb_WORK下签出您的仓库，以便您的工作可以访问它
      - 使用: 操作/签出@v4

      #使用运行器外壳运行单个命令
      - 姓名: 运行一行脚本
运行: 回声你好，世界！

      #使用runners shell运行一组命令
      - 姓名: 运行多行脚本
运行: |
回声添加要构建的其他操作，
回声测试，并部署您的项目。
